gbn/gbn_conn.go, gbn/queue.go
Turns out, the ping keepalive ticker was never started. This PR:
- starts the ping ticker
- cleans up the tickers on gbn close
- ensures that NACK is handled properly for the case where the peer received the entire queue successfully.
=> gbn: ping and Nack fix

cmd/wasm-client/go.mod, cmd/wasm-client/go.sum, cmd/wasm-client/lnd_conn.go, cmd/wasm-client/main.go, example/index.html, mailbox/client.go, mailbox/client_conn.go
In this PR, we expose the connection status of the Client so that callers can check if the status is in one of the following categories:
- **ConnStatusNotConnected:** the client is not connected at all this is likely due to the mailbox server being down.
- **ConnStatusSessionNotFound:** the connection to the mailbox server was successful but that the mailbox with the given ID was not found. This either means that the server is down, that the session has expired or that the user entered passphrase was incorrect.
- **ConnStatusSessionInUse:** the connection to the mailbox server was successful but that the stream for the session is already occupied by another client.
- **ConnStatusConnected:** ConnStatusConnected indicates that the connection to both the mailbox server and end server was …
=> multi: expose connection status

cmd/wasm-client/config.go, cmd/wasm-client/main.go, example/index.html
In this commit, the way in which the local and remote keys are specified
is changed. Instead of passing them in as command line arguments to the
binary, they are instead passed in as parameters to the ConnectServer
function.
This change allows the wasm binary to be pre-loaded and then only 
providing the keys afterwards. Rather than needing to provide the keys at 
load time.
=> wasm: pass keys in as parameters to ConnectServer

cmd/wasm-client/lnd_conn.go, cmd/wasm-client/main.go, itest/client_harness.go
In this commit, we add a WithBlock client dial option so that the
connection is not returned until the connection has been established
(ie, handshake is complete)
=> cmd/wasm-client: make client connection blocking

cmd/wasm-client/main.go, example/index.html, mailbox/client_conn.go
fixes #46 
When compiled in wasm, errors are thrown when attempting to close a websocket connection with `StatusGoingAway`. Things work properly if `StatusNormalClosure` is used instead. 
The example client is updated with `Disconnect` and `Reconnect` buttons to demonstrate that disconnect/reconnect now works.
=> multi: change websocket close status

itest/client_harness.go, itest/server_harness.go, mailbox/conndata.go
In this commit, we adjust the itests to send authData from the server to
the client and fail the test if the client does not receive the correct
authData from the server.
=> multi: send authData in itests

cmd/wasm-client/lnd_conn.go, cmd/wasm-client/main.go, itest/client_harness.go, itest/connection_test.go, itest/server_harness.go, mailbox/client.go, mailbox/client_conn.go, mailbox/server.go, mailbox/server_conn.go
Add server connection status info so that a caller of the Server can get informed about changes in the Server's connection. The 3 statuses differ from the Client connection statuses. They are as follows:
- `ServerConnStatusNotConnected`: the server is not connected to the mailbox. This means it is either the mailbox is down or that the server is busy re-connecting to it.
- `ServerConnStatusInUse`: A client is currently connected to the server
- `ServerConnStatusIdle`: the server is connected to the mailbox and ready to accept a connection but there is no client currently connected.
=> multi: server connection status

example/index.html
Adds buttons to the example html page to test calling the RPCs of `lnd` sub-servers. At the moment. these buttons will always be disabled due to the sub-server permissions not being added to the session macaroon created by `litd`. Once https://github.com/lightninglabs/lnc-web/issues/60 is resolved, these buttons should become enabled to properly test all of the sub-servers.
=> example: add buttons for LND RPC sub-servers

Makefile, cmd/wasm-client/permissions.go
In this commit, all the rpc subserver tags of LND are included in the
build so that the permissions of all the subservers can be extracted.
These permissions are then included in the permissions list used by the
`HasPermissions` function.
This is a temporary work around for now. I would like to open a PR in LND that exports 
the perms of the various subservers and perhaps also puts them all in a single directory 
so that we only need to import that. 
This PR along side https://github.com/lightninglabs/lightning-terminal/pull/413, addresses https://github.com/lightninglabs/lnc-web/issues/60
https://github.com/lightninglabs/lightning-node-connect/pull/54 can be used to test this
=> Makefile+wasm-client: add LND subserver perms

cmd/wasm-client/main.go, example/index.html
This commit updates the HasPermissions function to account for the case where the session has custom permissions which would specify "uri" as the permission entity and the actual URI as the permission action.
works with https://github.com/lightninglabs/lightning-terminal/pull/438
=> wasm: update HasPermissions to account for custom perms

mobile/mobile.go
Previous usage of the mutex in `ConnectServer` was causing a lock-up, conflicting with our polling calls to `IsConnected`. This more conservative approach fixes the issue.
=> mobile: ConnectServer: use mutex more conservatively

Makefile
This is required to prevent developers from manually changing their Foundation imports after build LNC mobile for iOS
=> Makefile: fix for iOS library import

.gitignore, Dockerfile-wasm, Makefile
```
SHA256(reproducible-builds/wasm-client.wasm)= 5d34b35fc255813b27d0abb75751fd02670c6c8556420d299cca6074626a86ba
```
=> Reproducible builds: WASM

Makefile
I missed this in my review of #66 
pertinent commit: https://github.com/lightninglabs/lightning-node-connect/pull/66/commits/38d34d92550dc25391af64cb661a834058da19a5
=> Makefile: apple: accomodate move of mobile to go module

cmd/wasm-client/main.go, example/index.html
Currently, the JS callbacks for `onlocalprivcreate`,  `onremotekeyreceive`, and `onauthdata` must be on the JS global scope for the WASM to call them. This adds a potential for race conditions when connecting to multiple nodes simultaneously because each connection will share the same callback functions that are defined on the global scope. Depending on the order in which the connections are established and callbacks are called, the local/remote keys returned may be associated with the wrong connection.
This PR allows the app to specify callbacks nested under a JS object, ex: `'--onauthdata=myapp.onAuthData'`. The app would have needed to create the nested object like this, for example:
```js
window['myapp'] = {
onAuthData: function(data) { ... }
}
```
The app can also leverage the …
=> wasm: allow non-global scope callbacks

Makefile, RELEASE.md, scripts/release.sh
This PR documents the release process and adds a small script to automate some of the steps.
=> doc: automate and document release process

.golangci.yml, itest/connection_test.go, itest/hashmailserver_harness.go, itest/test_harness.go
This PR exports the `HashmailHarness` struct, so that it can be used as an external dependency to setup a local mail server.
=> itest: export HashmailHarness struct

.golangci.yml, gbn/gbn_client.go, gbn/gbn_conn.go, mailbox/server.go
Update linter rules & fix some issues.
=> .golangci: update linter rules

gbn/config.go, gbn/gbn_client.go, gbn/gbn_conn.go, gbn/gbn_server.go, gbn/options.go, gbn/queue.go, gbn/queue_test.go, mailbox/client.go, mailbox/client_conn.go, mailbox/log.go, mailbox/server.go, mailbox/server_conn.go
This PR introduces a prefixed logger which is then passed to the client and server so that
their logs are prefixed with `(client)` and `(server)` so that we dont have to manually use
the `isServer` variable in logs. 
Then, some variables are moved out of the GBN struct and into a new `config` struct.
depends on #92
=> gbn+mailbox: cleanup & prefixed logger

.golangci.yml, gbn/config.go, gbn/gbn_conn.go, gbn/options.go, gbn/queue.go, gbn/queue_test.go, gbn/syncer.go, gbn/syncer_test.go, mailbox/client_conn.go
Fixes #89 
This PR addresses the packeting resend bug through a sender only side fix.
This PR ensures that after we have resent the queue, we will wait until we know that both parties are in sync before we continue to send new packets. This ensures that we don't end up in an indefinitely resend loop due to latency and delayed NACKs by the other party, which could happen prior to this commit.
To understand why we need to await the awaited ACK/NACK after resending the queue, consider the following scenario:
1. Alice sends packets 1, 2, 3 & 4 to Bob.
2. Bob receives packets 1, 2, 3 & 4, and sends back the respective ACKs.
3. Alice receives ACKs for packets 1 & 2, but due to latency the ACKs for packets 3 & 4 are delayed and aren't received until Alice resend timeout has passed, which leads …
=> gbn: Sender side only packeting resend bug fix

RELEASE.md
In this PR, we update the release notes with extra information for the release process that's currently missing.
This PR adds an extra system requirement, instructions of how to install NDK in Android Studio as well as instructions of how to generate an Open Timestamp.
Happy to address any feedback!
=> doc: update release notes

gbn/config.go, gbn/gbn_client.go, gbn/gbn_conn.go, gbn/gbn_server.go, gbn/options.go, gbn/queue.go, gbn/queue_test.go, gbn/syncer.go, gbn/syncer_test.go, gbn/timeout_manager.go, gbn/timeout_manager_test.go, itest/client_harness.go, itest/connection_test.go, mailbox/client_conn.go, mailbox/server_conn.go
Based on #87
This PR updates the resend timeout to be dynamically set based on how long it took for the other party to respond during the handshake process.
The timeout is set to the time it took for the server to respond multiplied by the resendMultiplier, unless the duration is shorter than the default resend timeout. If the the resend timeout has been manually set, the resend timeout will always be set to that value, and won't be dynamically set.
Prior to this PR, the timeout before a client resends the queue of packets was always a fixed value. This fixed timeout isn't suitable for all clients as the latency for different clients varies.
=> gbn: set resend timeout dynamically

cmd/wasm-client/log.go, cmd/wasm-client/main.go, example/index.html
In this PR, we add a fix that solves the error that the wasm-client freezes when attempting to close the sockets when disconnecting.
I've also added a commit to add the `gbn` subsystem to the wasm-client's logger. This simplifies debugging errors quite a lot. Let me know if you don't think that commit is worth including though :)
=> Fix WASM-client disconnection error

gbn/queue.go, gbn/syncer.go, gbn/timeout_manager.go
This PR makes the logger more informative in `debug` level for the gbn packet, and also way less verbose as it won't log the current `resendTimeout` `handshakeTimeout` when the values are fetched, but instead when they are set.
The logger is also updated to inform when packets are resent even under `debug` log level.
=> gbn: make logger more informative in `debug` level

cmd/wasm-client/main.go
When attempting to call new RPC methods, the frontend would hang without providing any useful debugging information, making it difficult to diagnose issues with RPC registration and execution.
Enhanced the logging and debugging capabilities of the WASM client's RPC system by:
1. Adding comprehensive logging for RPC method validation and execution
2. Adding visibility into the available RPC methods in the registry
3. Improving error messages with more context
- Added debug logging to show all available RPC methods in the registry when an RPC call is attempted
- Enhanced error logging for RPC validation checks
- Added panic recovery with stack traces for RPC execution
- Improved logging for both successful and failed RPC calls
To test these changes:
1. Set debug level logging
2. Attempt to …
=> wasm: detailed rpc logs

cmd/wasm-client/main.go
Additional modifications from https://github.com/lightninglabs/lightning-node-connect/pull/110
=> wasm: detailed rpc logs nits
